apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ze3pjl81t-go
  janus-idp.io/tekton: ze3pjl81t-go
  backstage.io/kubernetes-id: ze3pjl81t-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ze3pjl81t-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
