apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ze3pjl81t-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ze3pjl81t-go 
  name: ze3pjl81t-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ze3pjl81t-go 
